### ISSUE TITLE
Need to handle the case of JS `set`ting a value for a setting object

### ISSUE THREAD

**Issue by joyously** [dingo-d/wordpress-theme-customizer-extra-custom-controls#1]
The following line is setting up event handlers for the controls, but there is a case that is not covered.

https://github.com/dingo-d/wordpress-theme-customizer-extra-custom-controls/blob/d0549a5c4cabe37556727a5ea66d5443b70c9a06/inc/customizer/js/custom-controls.js#L15

If I write a custom control to reset to default values (or core provides one), it will likely be by calling `setting.set(value)` for each of the setting objects. This change is not handled, and needs to have the HTML single fields reflect what the multi field setting was set to.

**Comment by joyously** [comment]
This example code from a talk by Weston Ruter shows what is needed, I think. You have to `bind` a function to be called when the setting value changes.
[
Customizer Workshop 2017](https://docs.google.com/presentation/d/1AlQEROZ1-wAK8tXGDOw3aKwC_p1lATgY_t7fjZn9EM4/edit#slide=id.g1b01d11f4d_2_24)

**Comment by dingo-d** [comment]
But this is a custom control - if you write a custom control that will reset to default values, shouldn't you just handle this in a custom way? 

Not sure I understand the issue here. Can you explain it a bit more, perhaps with the example?

**Comment by joyously** [comment]
This custom control needs to do the appropriate thing when the `control.setting.set()` function is called. In other words, it needs to put the corresponding state into the visual elements.
In the example code, the `updateButton` function toggles a class to match what the new value is (that was `set()`). 
For your code, if core implements a reset feature that calls your `setting.set(newval)`, the individual input fields will not show that new value.  

Yes, "this is a custom control", and that is why it needs a custom way to handle the value that is `set()`. The basic core controls are always showing what their value is (it's a one to one relationship). It's the custom controls that do things differently, so need more code to make visual always match the setting's value.

**Comment by dingo-d** [comment]
Honestly, I haven't kept up with the custom customizer control in a while, so I'll have to revisit this. But thanks for the heads up, I'll look at the core implementation and see how to implement it in the custom controls. :+1:
