### ISSUE TITLE
Usage for plugin

### ISSUE THREAD

**Issue by andrasguseo** [dingo-d/wordpress-theme-customizer-extra-custom-controls#2]
https://github.com/dingo-d/wordpress-theme-customizer-extra-custom-controls/blob/d0549a5c4cabe37556727a5ea66d5443b70c9a06/inc/customizer/customizer.php#L21

How about using this, in case someone wants to use it in a plugin, and not a theme:
`require_once dirname( __FILE__ ) . '/custom-controls.php' ;`

**Comment by dingo-d** [comment]
Sure, that could work as well, but, usually, the customizer is used in a theme, so it makes more sense to use it this way.

Either way should work if I'm not mistaken :)
