### ISSUE TITLE
Issue related to $this->value()

### ISSUE THREAD

**Issue by Kastlebrick** [dingo-d/wordpress-theme-customizer-extra-custom-controls#4]
I may be missing something but I am having issues related to `$this->value()` (I think) in [This Line](https://github.com/dingo-d/wordpress-theme-customizer-extra-custom-controls/blob/d0549a5c4cabe37556727a5ea66d5443b70c9a06/inc/customizer/custom-controls.php#L372). $this->value() appears to be empty, so where do I get my default settings from?

I used add_option() to create the default values to the database, prior to your code running) and that's where it would be saved, but I was thinking $this->value() should get those values but they do not.. 

The margin, padding, content boxes appear in the Appearance > Customize section but there is just a - dash 

**[Also using class Box_Model](https://github.com/dingo-d/wordpress-theme-customizer-extra-custom-controls/blob/d0549a5c4cabe37556727a5ea66d5443b70c9a06/inc/customizer/customizer.php#L255)

**Comment by dingo-d** [comment]
The `$this` will refer to the current class, but also all the inherited public properties and methods from the parent class. In this case, it's the [`WP_Customize_Control`](https://developer.wordpress.org/reference/classes/wp_customize_control/) class.

Do note that this package hasn't been updated in 6 years or so, so I really cannot guarantee that it will work with the latest WP versions.

In fact, I'd suggest you don't use Customizer API anymore, as it will most likely be replaced with [global styles](https://make.wordpress.org/design/handbook/focuses/global-styles/), or something related with [FSE](https://fullsiteediting.com/).

As such, I cannot spend time in figuring out what might be wrong with this, sorry.

**Comment by Kastlebrick** [comment]
Thanks for the quick reply.. and I understand the age, I'm just glad you responded at all! (some don't)

> In fact, I'd suggest you don't use Customizer API anymore,

While you may feel this way, in general, this is for my own custom theme.. and I'm using it for the Themes default content margins and spacing (like titles, text and images). Just needed a nice way to do the box model interface. Thanks for that too!

That said, I have worked through the issue and I'm almost done with that section of development.

~Best!
